import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { isoDateOffset, todayIsoDate } from "@/lib/date";
import type { TeamLite } from "@/components/types";
import { TeamBadge } from "@/components/TeamBadge";
import { SectionHeading } from "@/components/site/SectionHeading";

export const revalidate = 60;

type NewsRow = {
  id: number;
  source: string;
  source_url: string | null;
  outlet: string;
  author: string | null;
  headline: string | null;
  summary: string;
  game_id: number | null;
  team_ids: number[];
  player_ids: number[];
  is_engine_take: boolean;
  published_at: string;
};

type PlayerLite = {
  id: number;
  first_name: string;
  last_name: string;
  team_id: number | null;
};

export default async function NewsPage() {
  const supabase = await createSupabaseServerClient();

  // "This week" window — yesterday through today + 7 to catch overnight pubs
  // for last night's games plus the full upcoming slate.
  const today = todayIsoDate();
  const start = isoDateOffset(today, -1);
  const startIso = `${start}T00:00:00Z`;

  const { data: rowsRaw } = await supabase
    .from("news_items")
    .select(
      "id, source, source_url, outlet, author, headline, summary, game_id, team_ids, player_ids, is_engine_take, published_at",
    )
    .gte("published_at", startIso)
    .order("published_at", { ascending: false })
    .limit(60);
  const rows = (rowsRaw ?? []) as NewsRow[];

  const teamIds = new Set<number>();
  const playerIds = new Set<number>();
  for (const r of rows) {
    for (const id of r.team_ids ?? []) teamIds.add(id);
    for (const id of r.player_ids ?? []) playerIds.add(id);
  }
  const [{ data: teams }, { data: players }] = await Promise.all([
    teamIds.size
      ? supabase
          .from("teams")
          .select("id, abbreviation, full_name")
          .in("id", [...teamIds])
      : Promise.resolve({ data: [] as TeamLite[] }),
    playerIds.size
      ? supabase
          .from("players")
          .select("id, first_name, last_name, team_id")
          .in("id", [...playerIds])
      : Promise.resolve({ data: [] as PlayerLite[] }),
  ]);
  const teamById = new Map(
    ((teams ?? []) as TeamLite[]).map((t) => [t.id, t] as const),
  );
  const playerById = new Map(
    ((players ?? []) as PlayerLite[]).map((p) => [p.id, p] as const),
  );

  const writerItems = rows.filter((r) => !r.is_engine_take);
  const engineItems = rows.filter((r) => r.is_engine_take);

  return (
    <div className="mx-auto max-w-5xl px-4 sm:px-6 py-10 space-y-10 fade-up">
      <SectionHeading
        eyebrow="NBA · This Week"
        title={
          <>
            What pundits are{" "}
            <span
              style={{
                background:
                  "linear-gradient(180deg, #FFE066 0%, #FFB800 100%)",
                WebkitBackgroundClip: "text",
                backgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}
            >
              saying
            </span>
          </>
        }
      />
      <p className="text-sm text-muted-foreground -mt-6">
        Short takes from reputable NBA writers on this week&apos;s slate. Every
        item links back to the source — nothing here is invented. If no writer
        has covered a matchup yet, the TrustMeBro engine fills the gap with a
        clearly-labelled preview.
      </p>

      {writerItems.length === 0 && engineItems.length === 0 ? (
        <EmptyState />
      ) : null}

      {writerItems.length > 0 ? (
        <section className="space-y-4">
          <SubSectionTitle title="Pundits" count={writerItems.length} />
          <div className="grid gap-4">
            {writerItems.map((it) => (
              <NewsCard
                key={it.id}
                item={it}
                teamById={teamById}
                playerById={playerById}
              />
            ))}
          </div>
        </section>
      ) : null}

      {engineItems.length > 0 ? (
        <section className="space-y-4">
          <SubSectionTitle title="TrustMeBro engine takes" count={engineItems.length} />
          <p className="text-xs text-muted-foreground -mt-2">
            Generated by our analysis engine. Not a writer quote.
          </p>
          <div className="grid gap-4">
            {engineItems.map((it) => (
              <NewsCard
                key={it.id}
                item={it}
                teamById={teamById}
                playerById={playerById}
              />
            ))}
          </div>
        </section>
      ) : null}
    </div>
  );
}

function SubSectionTitle({ title, count }: { title: string; count: number }) {
  return (
    <div className="flex items-baseline justify-between gap-3">
      <h2 className="font-display uppercase text-xl sm:text-2xl tracking-tight">
        {title}
      </h2>
      <span className="text-[11px] uppercase tracking-[0.22em] text-muted-foreground">
        {count} item{count === 1 ? "" : "s"}
      </span>
    </div>
  );
}

function NewsCard({
  item,
  teamById,
  playerById,
}: {
  item: NewsRow;
  teamById: Map<number, TeamLite>;
  playerById: Map<number, PlayerLite>;
}) {
  const teams = (item.team_ids ?? [])
    .map((id) => teamById.get(id))
    .filter((t): t is TeamLite => !!t)
    .slice(0, 3);
  const players = (item.player_ids ?? [])
    .map((id) => playerById.get(id))
    .filter((p): p is PlayerLite => !!p)
    .slice(0, 3);

  const when = new Date(item.published_at);
  const wenLabel = Number.isFinite(when.getTime())
    ? when.toLocaleString("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit",
      })
    : null;

  const isExternal = item.source_url?.startsWith("http");

  return (
    <article className="card-tmb p-5 space-y-3 hover:-translate-y-0.5 transition-transform">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2">
          <span
            className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.16em] ring-1 ${
              item.is_engine_take
                ? "bg-primary/15 text-primary ring-primary/30"
                : "bg-foreground/5 text-foreground/85 ring-border"
            }`}
          >
            {item.is_engine_take ? "Engine Take" : item.outlet}
          </span>
          {item.author ? (
            <span className="text-xs text-muted-foreground">
              by <span className="text-foreground/85">{item.author}</span>
            </span>
          ) : null}
        </div>
        {wenLabel ? (
          <span className="text-[11px] text-muted-foreground tabular-nums">
            {wenLabel}
          </span>
        ) : null}
      </div>

      {item.headline ? (
        <h3 className="font-display uppercase text-base sm:text-lg leading-snug tracking-tight">
          {item.headline}
        </h3>
      ) : null}
      <p className="text-sm text-foreground/85 leading-relaxed">
        {item.summary}
      </p>

      {(teams.length > 0 || players.length > 0) ? (
        <div className="flex items-center gap-2 flex-wrap pt-1">
          {teams.map((t) => (
            <Link
              key={`t-${t.id}`}
              href={`/teams/${t.id}`}
              className="inline-flex items-center gap-1.5 rounded-full bg-foreground/5 px-2 py-1 text-[11px] hover:bg-foreground/10 transition-colors"
            >
              <TeamBadge team={t} size={16} />
              <span className="text-foreground/85">{t.abbreviation}</span>
            </Link>
          ))}
          {players.map((p) => (
            <Link
              key={`p-${p.id}`}
              href={`/players/${p.id}`}
              className="inline-flex items-center gap-1 rounded-full bg-foreground/5 px-2 py-1 text-[11px] text-foreground/85 hover:bg-foreground/10 transition-colors"
            >
              {p.first_name.charAt(0)}. {p.last_name}
            </Link>
          ))}
        </div>
      ) : null}

      <div className="flex items-center justify-between gap-3 pt-1">
        {item.game_id ? (
          <Link
            href={`/games/${item.game_id}`}
            className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground hover:text-foreground/85 transition-colors"
          >
            Game details →
          </Link>
        ) : (
          <span />
        )}
        {item.source_url ? (
          isExternal ? (
            <a
              href={item.source_url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[11px] uppercase tracking-[0.18em] text-primary hover:opacity-80 transition-opacity"
            >
              Read on {item.outlet} ↗
            </a>
          ) : (
            <Link
              href={item.source_url}
              className="text-[11px] uppercase tracking-[0.18em] text-primary hover:opacity-80 transition-opacity"
            >
              Read more →
            </Link>
          )
        ) : null}
      </div>
    </article>
  );
}

function EmptyState() {
  return (
    <div className="card-tmb p-10 text-center space-y-3">
      <p className="text-foreground/85">
        No fresh writer commentary for this week yet.
      </p>
      <p className="text-xs text-muted-foreground">
        The hourly cron sweeps ESPN, Bleacher Report, Yahoo Sports, CBS Sports
        and (when configured) NewsAPI. New items will appear here as they
        publish.
      </p>
    </div>
  );
}
